### ISSUE TITLE
Volumes are not removed after PV is deleted with Delete reclaimPolicy 

### ISSUE THREAD

**Issue by bernardgut** [openebs/zfs-localpv#507] opened 2024-02-25 09:57 UTC
**What steps did you take and what happened:**

1. Create a PVC with a storageclass that has Retain as a reclaimPolicy, bind it to a pod
2. Delete the pod and PVC
3. Check the `kubectl get pv`, PV is still there with attributes `policy=Retain` and `status=Released` : All good 
4. Change the policy to `Delete` : `kubectl patch pv "$pv" -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}'`
5. The PV is instantly deleted. All good
6. Check `zfs list` : the volume is still there

**What did you expect to happen:**
Volume should be eventually deleted 

Example of `k get zv` for a deleted pv following the procedure above 30 min after deletion:

```
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  creationTimestamp: "2023-10-01T11:45:38Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2024-02-25T08:51:59Z"
  finalizers:
  - zfs.openebs.io/finalizer
  generation: 3
  labels:
    kubernetes.io/nodename: XXXX
  name: pvc-0c35a432-f9c2-4018-b978-7581fbb166c2
  namespace: openebs
  resourceVersion: "257193999"
  uid: b30ad8d7-aa44-43da-96b6-a1a814c1a43c
spec:
  capacity: "107374182400"
  compression: "off"
  dedup: "off"
  fsType: zfs
  ownerNodeID: XXXX
  poolName: XXXX/openebs
  volblocksize: 4k
  volumeType: DATASET
status:
  state: Ready

```

**Anything else you would like to add:**
not sure when the garbage collection runs but it's been 10 min and the volumes are still there. If it is just a case of me being impatient then you can discard this issue.

**Environment:**
- ZFS-LocalPV version : `app: openebs-zfs-controller chart: zfs-localpv-2.4.0`
- Kubernetes version (use `kubectl version`): `Server Version: v1.26.11+rke2r1`
- Kubernetes installer & version: `rke2 install script on bare-metal`
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.6 LTS

**Comment by bernardgut** [comment] 2024-02-28 22:28
4 days have passed and the garbage collector (?) still hasn't run. Can I safely delete the dangling volumes directly with `zfs destroy...` ? Or is this going to break my openebs-zfs/k8s storage ?

**Comment by niladrih** [comment] 2024-02-29 04:24
You can delete the ZFSVolume resource and the volume should be deleted.

On the other one, unfortunately the delete pathway is closely linked with the PVC delete event. the Kubernetes PV delete is a handled by the kubernetes-csi components, and not the ZFS drivers. The driver doesn't actually watch for PV's and doesn't logically map ZFSVolumes to PV's.

**Comment by niladrih** [comment] 2024-02-29 04:47
Duplicate of https://github.com/openebs/zfs-localpv/issues/404.

**Closed as completed by niladrih** 2024-02-29 04:47 UTC

**Comment by bernardgut** [comment] 2024-02-29 10:42
Thanks for the answer.

It is not a duplicate of #404. It is the opposite. If you read my original post at point 4, **I changed the reclaimPolicy to "Delete" on an unbound volume and the PV object was instantly garbage-collected and gone from the tree -- but the volume is still there**. 

NB: The Pod/PVC which were bound to this PV were deleted long ago and the PV was showing status `Released` before I did the reclaimPolicy change to `delete` through a patch operation.

Anyway, here is the current status :
1. I tried to delete the the dangling volumes with `k delete -n openebs zv ...`, like you suggested, and the delete operation hangs forever. 
2.  I assumed it was a similar issue on the finalizers than the one you usually see on PVs but with ZVs instead. So I tried to remove the finalizers there (since there is no PV associated with this ZV anyway, I dont have any other option) with `k -n openebs patch zv $zv --type=merge -p '{"metadata": {"finalizers": null}}'`: 

The results are not very conclusive: The delete operation at point 1. succeeded. **The zv object is gone from the tree too, but `zfs list` still shows the volume present in the storage pool.** Obviously those finalizers were needed... Maybe the delete operation hangs because you need to be root to actually run `zfs destroy` on the machine ? I dont know.

I assume the next step to get rid of the volume would be to manually delete the volume with `zfs destroy` -- which is what I did in this case -- but I have to do this for 150+ ZFSvolumes that were previously bound in my cluster. Is there no way to automate the deletion of the zfs volumes when the PVs are deleted ? From your answer I assume "NO". But what about when I delete the ZVs ?

From your anwer :
> The driver doesn't actually watch for PV's and doesn't logically map ZFSVolumes to PV's.

Does that mean the `reclaimPolicy` field on the PVs objects has absolutely no impact on ZFS storage behavior ? Is the behavior I observed in my original post the default behavior regardless of what you put in the PV/StorageClass `reclaimPolicy` fields ?

There is no `reclaimPolicy` field on ZFSVolumes so I am confused. I just want to understand how it works.

thanks 
Bernard

**Comment by niladrih** [comment] 2024-03-07 05:51
> Does that mean the reclaimPolicy field on the PVs objects has absolutely no impact on ZFS storage behavior

@bernardgut 
That is correct. This will be become clearer when we take a look at the design of a kubernetes CSI volume provisioner plugin.  The dynamic provisioning scheme limits user interactions to the PVC level. The PV (along with the underlying volume) is managed by the CSI provisioner plugin.

Once the retainPolicy is set to 'Retain' the PV and the volume are to be left behind after the PVC delete. This plugin makes use of the [CSI external provisioner](github.com/kubernetes-csi/external-provisioner) helper sidecar to interface with PVs and PVCs via gRPC CSI calls. The sidecar doesn't request for a 'DeleteVolume' call when the PV is deleted. The 'DeleteVolume' call is issued only for PVC delete. A 'Retain' configured PVC cannot follow any other workflow unless the configuration was altered at the PVC level. A 'Delete' patch on the PV would make the csi sidecar look for a PVC attached to it. When it can't find one, it will remove the PV object. However, a PV delete is not grounds for a CSI call. A 'Retain' PVC's artifacts are for the administrator to deal with. This is expected behavior for a CSI plugin.

However, you can raise a feature-request for a volume garbage collector, or better yet, you can contribute the feature yourself. This feature is beyond the scope of the simple CSI plugin behaviour set.

**Comment by bernardgut** [comment] 2024-03-08 13:20
This is super interesting. Thanks for the explanation. 

I think I understand what you mean. However, according tho this : https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/ :

>You can use finalizers to control [garbage collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/) of resources. For example, you can define a finalizer to clean up related resources or infrastructure before the controller deletes the target resource.

I can use the Finalizers to check dangling resources and delete them. So should I create a PR on the CSI plugin repo that updates the finalizer so that delete the volumes on the node when the `reclaimPolicy` is set to DELETE at deletion time ? Is that what you mean ? (Or is that something you would be interested in ?)

thanks
B.

**Comment by niladrih** [comment] 2024-03-14 21:28
> This is super interesting. Thanks for the explanation.
> 
> I think I understand what you mean. However, according tho this : https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/ :
> 
> > You can use finalizers to control [garbage collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/) of resources. For example, you can define a finalizer to clean up related resources or infrastructure before the controller deletes the target resource.
> 
> I can use the Finalizers to check dangling resources and delete them. So should I create a PR on the CSI plugin repo that updates the finalizer so that delete the volumes on the node when the `reclaimPolicy` is set to DELETE at deletion time ? Is that what you mean ? (Or is that something you would be interested in ?)
> 
> thanks B.

We'd have to create a garbage collector which would run once in a while, and would try to find ZFSvolume resourcses without a PVC attached to it, and then try to find a PV attached to it. If no PV exists, it would delete the ZFSVolume, and that would trigger a delete for the underlying dataset.

**Comment by abuisine** [comment] 2024-06-21 15:53
Shouldn't the deletion of a PV, whether automatic or manual, typically result in data deletion? Wouldn't this be expected as the default behavior?

Currently, this requires administrators to understand the specifics of this CSI driver and to develop a cleanup strategy, either manually or through an unprovided tool. This seems to contradict the general principle of abstraction that Kubernetes usually offers.

It appears appropriate that the deletion of a ZFS filesystem or volume should occur at the time of the PV deletion (by default).
The Retain or Delete strategy is a setting for the internal Kubernetes PV management, and I have not seen a CSI driver that retains data post-PV deletion by default (except in cases of flawed or buggy implementations).
To my knowledge, the CSI specs/API provide all necessary events and calls to facilitate this.

I would be happy to contribute if needed, but could you please confirm your point of view ?
I believe that a garbage collecting scenario would be much more complex than an instant deletion scenario, though both would address the issue. Do you have a preference for one over the other?

**Comment by BlackDark** [comment] 2025-09-06 19:44
I tried to implement a POC for garbage collection for such volumes: https://github.com/BlackDark/openebs-zfs-cleanup-controller

Noticed that i have dangling around quite a few ZFSVolumes because I thought deleting PVs was enough.
