### ISSUE TITLE
refactoring needed to add support for go modules.

### ISSUE THREAD

**Issue by vaniisgh** [openebs/zfs-localpv#129] opened 2020-05-21 13:13 UTC
The following projects need help with refactoring to use go modules. 
[ ] https://github.com/openebs/zfs-localpv
[ ] https://github.com/openebs/node-disk-manager
[WIP] https://github.com/openebs/maya

_Originally posted by @kmova in https://github.com/openebs/openebs/issues/3040#issuecomment-630568725_

**Comment by pawanpraka1** [comment] 2020-05-27 08:20
duplicate of https://github.com/openebs/zfs-localpv/issues/126.

**Closed by pawanpraka1** 2020-05-27 08:20 UTC
