### ISSUE TITLE
Default value in values.yaml triggers warning message on install

### ISSUE THREAD

**Issue by jnels124** [openebs/zfs-localpv#474] opened 2023-09-18 19:08 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**
Install chart without warning messages

**Anything else you would like to add:**
log: `coalesce.go:223: warning: destination for hedera-mirror-common.zfs.zfsNode.additionalVolumes is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for hedera-mirror-common.zfs.zfsNode.initContainers is a table. Ignoring non-table value ([])`

**Environment:**
- ZFS-LocalPV version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by hrudaya21** [comment] 2023-09-19 10:48
@jnels124 What command you have used for installation ?
Following commands for installation doesn't show any such warning.
![image](https://github.com/openebs/zfs-localpv/assets/31165675/8b0ebc99-c1ff-4eeb-8fce-8993da910897)

**Comment by hrudaya21** [comment] 2023-09-19 11:55
Also tried the installed with helm, but not able to reproduce the problem. Please share the steps followed to reproduce this issue.

**Comment by sinhaashish** [comment] 2023-11-15 04:21
@jnels124 waiting for your reply here. If this is resolved then do share the steps

**Comment by avishnu** [comment] 2024-10-01 10:42
Closing this issue as it cannot be reproduced.

**Closed as completed by avishnu** 2024-10-01 10:42 UTC
Labels: triage/needs-information, triage/not-reproducible
