### ISSUE TITLE
mount point does not exist

### ISSUE THREAD

**Issue by chornlgscout** [openebs/zfs-localpv#112] opened 2020-05-13 15:44 UTC
openebs-zfs-node openebs-zfs-plugin says:
> time="2020-05-13T15:35:14Z" level=info msg="GRPC request: {\"target_path\":\"/var/snap/microk8s/common/var/lib/kubelet/pods/e133fcad-a7dd-459d-8bad-c555faf1170d/volumes/kubernetes.io~csi/pvc-b3f312c4-0f1d-4348-8196-dcb19bec206c/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"openebs.io/poolname\":\"lg-data\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1589384112805-8081-zfs.csi.openebs.io\"},\"volume_id\":\"pvc-b3f312c4-0f1d-4348-8196-dcb19bec206c\"}"
> E0513 15:35:14.275371       1 mount_linux.go:147] Mount failed: exit status 32
> Mounting command: mount
> Mounting arguments: -t ext4 -o defaults /dev/zvol/lg-data/pvc-b3f312c4-0f1d-4348-8196-dcb19bec206c /var/snap/microk8s/common/var/lib/kubelet/pods/e133fcad-a7dd-459d-8bad-c555faf1170d/volumes/kubernetes.io~csi/pvc-b3f312c4-0f1d-4348-8196-dcb19bec206c/mount
> Output: mount: /var/snap/microk8s/common/var/lib/kubelet/pods/e133fcad-a7dd-459d-8bad-c555faf1170d/volumes/kubernetes.io~csi/pvc-b3f312c4-0f1d-4348-8196-dcb19bec206c/mount: mount point does not exist.
> E0513 15:35:14.497336       1 mount_linux.go:147] Mount failed: exit status 32

**Environment:**
- ZFS-LocalPV dd059a2f435b4a32a8517c2133491d9d9f7f633e 
- Kubernetes 1.18.2
- Kubernetes microk8s 1.18
- OS Ubuntu 16.04.6 by way of multipass

**Comment by chornlgscout** [comment] 2020-05-13 19:34
Obviously, the openebs-zfs-node  openebs-zfs-plugin needs to mount the real kubelet directory at the real path. Modified zfs-operator.yaml with that mount, and all is well.

**Comment by pawanpraka1** [comment] 2020-05-14 04:37
@chornlgscout, can you describe a little bit about the setup? How you are using the ZFS-LocalPV? Is it a production or dev setup? What features you are using or looking for?

If possible, can you sign the adopters file for us and detail your use-case a bit? It will help us out when working with CNCF.  Here is the adopters file where a lot of users have already signed it : openebs/openebs#2719.

**Comment by chornlgscout** [comment] 2020-05-14 13:48
Briefly: Development POC, trying to port a legacy application using local zfs storage behind components including elasticsearch, kafka and zookeeper. We intend to dynamically allocate zvols to these components, to snapshot them on upgrade, and roll them back on rollback. Intent is for this to be a locally hosted production product.

I'd also like to be able to use shared local zvols for communal scratch space (e.g. shunting file based logs to filebeat), but that seems less likely.

**Comment by pawanpraka1** [comment] 2020-05-14 14:53
Thaks for sharing this @chornlgscout . The local shared zvols/dataset are in our roadmap (but not prioritized). We are also thinking of a solution where we identify/detect system dependencies and generate the operatore file accordinly, which will help users and ease their life. For example in this bug, we needed to modify the mount path in operator file, In some cases we need to do some OS specific stuff, which will be automated.

**Comment by pawanpraka1** [comment] 2020-05-15 08:33
adding the details from the issue https://github.com/openebs/zfs-localpv/issues/113  

```
Registration is sensibly targeted to /var/lib/kubelet, but the directory actually used by microk8s snap is /var/snap/microk8s/common/var/lib/kubelet. I resolved this by symlinking the actual location to the expected location.
```

**Comment by wirwolf** [comment] 2020-08-18 13:01
Rancher 2.4.5 
kubernetus  v1.18.3

MountVolume.NewMounter initialization failed for volume "pvc-45421d5d-b8fd-40d0-9918-32eab3547156" : path "/var/openebs/local/pvc-45421d5d-b8fd-40d0-9918-32eab3547156" does not exist
```

root@node-2:~# ls -alh /var/openebs/local/pvc-45421d5d-b8fd-40d0-9918-32eab3547156
total 8.0K
drwxrwxrwx 2 root root 4.0K Aug 18 13:05 .
drwxr-xr-x 3 root root 4.0K Aug 18 13:05 ..
root@node-2:~# 
```

**Comment by pawanpraka1** [comment] 2020-08-18 13:07
@wirwolf which storage engine you are using? does not look like you are using localpv zfs? Seems like you are using localpv hostpath storage engine?

**Comment by quexten** [comment] 2020-12-09 15:55
I have the same issue. I was doing some unrelated work on the cluster, rebooted and suddenly none of my pods which are using a zfs-localpv volume are starting, with the same error. 

```
  Warning  FailedMount       3m1s (x9 over 5m9s)    kubelet            MountVolume.SetUp failed for volume "pvc-343b4d66-a627-499d-99bf-0611dbd76789" : rpc error: code = Internal desc = rpc error: code = Internal desc = dataset: mount failed err : mount: /var/lib/kubelet/pods/a19a1a00-14e2-4642-bea0-9b222f4de615/volumes/kubernetes.io~csi/pvc-343b4d66-a627-499d-99bf-0611dbd76789/mount: mount point does not exist.
```

I manually created this path after which the pod started fine. But this is obviously not the correct solution.
Reinstalling openebs or destroying and re-creating my zpool did not work.
My storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
allowVolumeExpansion: true
parameters:
  recordsize: "4k"
  compression: "on"
  dedup: "off"
  fstype: "zfs"
  poolname: "data"
provisioner: zfs.csi.openebs.io
```
Other than that I installed it just like in the readme.

**Comment by pawanpraka1** [comment] 2020-12-09 16:17
@quexten this looks to be different issue. Can you elaborate a little bit about your cluster, is it on-prem cluster or the cluster is managed by any cloud provider? What is the k8s version you are using?

That directory normally gets created by the kubelet. I need to understand why it did not happen in your case.

**Comment by quexten** [comment] 2020-12-09 16:54
It is a testing cluster consisting of just a single node at the moment on a Ubuntu server. The Kubernetes version is 1.19.3. The ZFS-LocalPV version is the latest one from https://openebs.github.io/charts/zfs-operator.yaml . I've previously rebooted the node just fine with the mounts working afterwards. Sadly I'm not sure what I did to cause this to happen, so I'm not sure how to make this state reproducible. I just tried out openebs in LocalPVHostpath mode and this works fine, so the kubelet seems to create the directories.

**Comment by ahlgol** [comment] 2020-12-13 13:34
> It is a testing cluster consisting of just a single node at the moment on a Ubuntu server. The Kubernetes version is 1.19.3. The ZFS-LocalPV version is the latest one from https://openebs.github.io/charts/zfs-operator.yaml . I've previously rebooted the node just fine with the mounts working afterwards. Sadly I'm not sure what I did to cause this to happen, so I'm not sure how to make this state reproducible. I just tried out openebs in LocalPVHostpath mode and this works fine, so the kubelet seems to create the directories.

Also running ZFS-LocalPV with microk8s on a single node, and after a reboot this weekend the volumes won't get mounted. Have to create the pvc-.../mount manually. It has been running fine for 12 weeks before this, going through multiple reboots. Maybe its an upgrade microk8s that's causing trouble?

`Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-37+7ab055a22f5440", GitCommit:"7ab055a22f5440dbdcd1d41095b7db95d98fc1c3", GitTreeState:"clean", BuildDate:"2020-12-10T18:59:05Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by quexten** [comment] 2020-12-13 15:41
I'm not using microk8s and still got the issue, so it must be something in general with the updates. Before I got this issue I did run a full system software upgrade. Setting up a new cluster with Kubernetes 1.20.0 lead to the same issue.

**Comment by ahlgol** [comment] 2020-12-13 18:01
Could this be relevant? (from k8s 1.20 release notes)

`
For CSI drivers, kubelet no longer creates the target_path for NodePublishVolume in accordance with the CSI spec. Kubelet also no longer checks if staging and target paths are mounts or corrupted. CSI drivers need to be idempotent and do any necessary mount verification. (#88759, @andyzhangx) [SIG Storage]
`

**Comment by pawanpraka1** [comment] 2020-12-13 18:49
@ahlgol, yes that is the issue. We have already made the fix for that and it will be released in ZFS-LocalPV 1.2.0 (due on 15th of Dec 2020). You can try out the RC2 yaml `https://raw.githubusercontent.com/openebs/charts/2c77087c93fd9088984dc6dbe784ff8c6a6c8100/2.4.0/zfs-operator-RC2.yaml`. let me know if that fixes the issue.

**Comment by ahlgol** [comment] 2020-12-14 10:39
@pawanpraka1, Yup, the "mount does not exist" is gone now! :+1: Still getting some `verifyMount: device already mounted at` that I have to unmount manually from previous pods, and I have some new permission issues on mariadb:10 containers, but it might be unrelated. Will dig deeper tonight. Thanks!

**Comment by pawanpraka1** [comment] 2020-12-14 11:54
thanks @ahlgol, There are 3 things here 

1. `mount does not exist` issue is fixed :+1:.  

2.  Got a new issue `verifyMount: device already mounted at` and you have to unmount manually from previous pods. This is interesting. How did you get into this issue? This should not hapen as after reboot the volume will get automatically umounted?
Can you elaborate the step to reproduce this?

3. You have permission issues on mariadb. Let me know if you need any help here.

@quexten could you also try out the RC2 yaml `https://raw.githubusercontent.com/openebs/charts/2c77087c93fd9088984dc6dbe784ff8c6a6c8100/2.4.0/zfs-operator-RC2.yaml` and let me know if that is working for you.

**Comment by ahlgol** [comment] 2020-12-14 18:12
Right!

for 2) 

When I stop/start microk8s or reboot the machine the PVs are already mounted when the pods tries to start (stopping microk8s doesn't remove the mount). Not sure what mounts if after reboot yet as they obviously aren't present in fstab... Will investigate further.

Error message in full:
`MountVolume.SetUp failed for volume "pvc-5033d122-dcca-466e-88ba-bdb8bd3a8bce" : rpc error: code = Internal desc = rpc error: code = Internal desc = verifyMount: device already mounted at [/host/var/snap/microk8s/common/var/lib/kubelet/pods/b8990882-5093-4786-8341-af58891c3e0e/volumes/kubernetes.io~csi/pvc-5033d122-dcca-466e-88ba-bdb8bd3a8bce/mount /var/snap/microk8s/common/var/lib/kubelet/pods/b8990882-5093-4786-8341-af58891c3e0e/volumes/kubernetes.io~csi/pvc-5033d122-dcca-466e-88ba-bdb8bd3a8bce/mount]`

The pods fail to start after this, even though the volume is actually mounted at the correct mount point...

After a manual unmount, the pods (eventually) start but I still have permission voes... will try to understand them now.

**Comment by pawanpraka1** [comment] 2020-12-15 02:53
> Not sure what mounts if after reboot yet as they obviously aren't present in fstab

@ahlgol, I think, probably in k8s 1.20, the kubelet is asking more than once for the volumes to be mounted . We can check the ZFS-LocalPV daemonset log for the same and see if there is successful mount request for the same volume at the same path. Can you shared the full log to confirm this?

**Comment by ahlgol** [comment] 2020-12-15 07:47
Sure thing.

[csi-node-driver-registrar.log](https://github.com/openebs/zfs-localpv/files/5694099/csi-node-driver-registrar.log)
[openebs-zfs-plugin.log](https://github.com/openebs/zfs-localpv/files/5694100/openebs-zfs-plugin.log)

**Comment by pawanpraka1** [comment] 2020-12-15 10:26
@ahlgol not able to find any trace of the mount request. It was failing since the beginning in the log. We have made a patch fix for the idempotency in the 1.2.1 release. We are finishing the release work for that. Here is yaml `https://raw.githubusercontent.com/openebs/charts/5669b65f17c026620c5e3369a9a1328c3c14f76c/zfs-operator.yaml`. This should fix the issue. But I am still curious to know how it is getting mounted after reboot.

**Comment by ahlgol** [comment] 2020-12-15 22:29
Thanks! Rebooting without issue now. :+1: 

Not sure what went wrong either, and the mount failures where intermittent, mounting correctly sometimes. The mounts weren't created when disabling the microk8s service, so it was nothing external. Possibly a timing issue or network issues (the dns runs in microk8s as well, so it wasn't working) caused a hiccup, which restarted pods and so zfs-plugin tried to mount the volumes twice...

My permission problems seem to stem from the fact that the mounts are now created with a umask of 000. Chmoding it to 100 lets mariadb start. Not sure what microk8s set it to by default before (which worked) but will have to go looking for the best ways to set it in the correct umask in the pod spec I guess. ^_^

Many thanks again!

**Comment by pawanpraka1** [comment] 2020-12-16 04:52
> Thanks! Rebooting without issues now.

Nice!!

> The mounts weren't created when disabling the microk8s service, so it was nothing external.

I guess, that is becasue the change in kubernetes 1.20 stopped creating the mount directory and also stopped checking if the volume is already mounted don't ask the CSI driver to mount again. There are a lot of CSI driver which depends on that. This must have broken many CSI drivers.

> My permission problems seem to stem from the fact that the mounts are now created with a umask of 000. 

Not sure, the fix I made to solve the above issue is to create the directory with 777 permission. I see k8s Hostpath driver creates 
 the mountpath with 0755 (https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L141) permission. I have made a docker image `pawanpraka1/zfs-driver:perm` with that change. Could you update the zfs-operatore yaml with this image. To do that, replace `openebs/zfs-driver:1.2.1` to  `pawanpraka1/zfs-driver:perm`, there two places where we need to change this.

**Comment by ahlgol** [comment] 2020-12-17 08:44
Sorry for taking some time to try it out - it works great! :+1: 

However, I tried to switch back to the 1.2.1 driver and it seems to create a 755 umask as well now. Not sure what I did wrong before :-/

Thanks for the help! :-)

**Comment by pawanpraka1** [comment] 2020-12-17 08:47
@ahlgol can you confirm? 1.2.1 is working for you, you did not need to try `pawanpraka1/zfs-driver:perm`.

**Comment by pawanpraka1** [comment] 2020-12-17 13:54
> However, I tried to switch back to the 1.2.1 driver and it seems to create a 755 umask as well now.

@ahlgol this is very strange. We never hit this issue in our e2e pipeline. Any changes in the setup since you hit the issue last time?

**Comment by ahlgol** [comment] 2020-12-17 13:59
I haven't investigated this fully, but if I understand this correctly, the mounts for existing PVs were still created with 000 umask. I tried pawanpraka1/zfs-driver:perm with same result. Then I removed the complete namespace and it created a mount with 755 umask. I then moved back to openebs/zfs-driver:1.2.1 just to verify, and after namespace removal (afaikt) it created a mount with 755 as well.

**Comment by pawanpraka1** [comment] 2020-12-17 15:17
The only different between `openebs/zfs-driver:1.2.1` and `pawanpraka1/zfs-driver:perm` is mount difrectory permission. the `1.2.1` image creates the directory with 0000 permission where `perm` image creates the directory with 0755 permission. Not sure why it was not working with 1.2.1 in your case and suddenly started working now :thinking: .

**Comment by pawanpraka1** [comment] 2020-12-18 06:51
@ahlgol Closing this issue for now. Please reopen a new bug if you face any issues.

**Closed by pawanpraka1** 2020-12-18 06:51 UTC
Labels: help wanted, pr/documentation-pending, project/community

**Comment by ahlgol** [comment] 2020-12-21 18:30
@pawanpraka1 Sure thing! I'm sorry I don't have more time to put on this right... too many Christmas deadlines ^_^ Curiously I noticed that most of my "old" mounts had reverted to 000 a day ago or so, leaving only the new mount with 755. However, when I notice the problem I can just run a `find` command that chmods all the mount dirs - no biggie. Thanks for your help and all your effort! Will open a new ticket if I get the time to troubleshoot this further. Happy Holidays!

**Comment by pawanpraka1** [comment] 2020-12-22 04:13
Thanks @ahlgol, Let me know if you need any help troubleshooting it. I am also very curious about the problem you are facing. We are not facing that problem on our local setup or in our e2e pipeline. I already have a PR (https://github.com/openebs/zfs-localpv/pull/262) for this which was used to build `pawanpraka1/zfs-driver:perm` image, hoping that will fix the issue. Happy Holidays and Merry Christmas!!
